In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

# Data Understanding

### Column Dictionary

| # | Column | Description | Data Type | Values / Range |
|---|---|---|---|---|
| 1 | `transaction_id` | Unique identifier of the transaction | Text (ID) | e.g. `TXN-20230000000` |
| 2 | `account_id` | Identifier of the bank account that made the transaction | Text (ID) | e.g. `ACC-229636759` |
| 3 | `customer_id` | Identifier of the customer who owns the account | Text (ID) | e.g. `CUST-616210` |
| 4 | `customer_name` | Full name of the customer (not unique — names repeat across customers) | Text | 400 distinct names |
| 5 | `account_type` | Type of bank account | Categorical | Checking, Savings, Credit Card, Loan, Mortgage, Investment |
| 6 | `account_status` | Current status of the account | Categorical | Active, Dormant (inactive), Frozen (blocked), Closed |
| 7 | `transaction_type` | Kind of financial operation performed | Categorical | Deposit, Withdrawal, Transfer, Payment, Refund, Fee, Interest |
| 8 | `transaction_date` | Date the transaction took place | Date (stored as text) | 2022-01-01 → 2025-12-31 |
| 9 | `amount` | Value of the transaction (positive or negative) | Numerical (float) | -4,737,986.89 → 4,091,721.74 |
| 10 | `currency` | Currency of the transaction amount | Categorical | EUR, USD, GBP, CHF, PLN |
| 11 | `balance_after` | Account balance after the transaction | Numerical (float) | 107.18 → 499,987.45 |
| 12 | `transaction_channel` | Channel through which the transaction was made | Categorical | Online, Mobile App, ATM, Branch, Phone, SEPA, Direct Debit |
| 13 | `branch_city` | German city of the bank branch handling the account | Categorical | 15 cities (Berlin, Munich, Hamburg, Frankfurt, …) |
| 14 | `merchant_name` | Merchant or beneficiary of the transaction | Categorical | REWE, Lidl, Aldi, EDEKA, Shell, Amazon, Netflix, MediaMarkt, Deutsche Bahn |
| 15 | `payment_method` | Method used to pay | Categorical | Debit Card, Credit Card, Bank Transfer, SEPA, Cash |
| 16 | `is_international` | Whether the transaction crossed borders | Boolean | True / False |
| 17 | `fee_amount` | Fee charged by the bank on the transaction | Numerical (float) | 0 → 25 |
| 18 | `risk_score` | Automated risk rating of the transaction (higher = riskier) | Numerical (float) | 0 → 100 |
| 19 | `fraud_flag` | Whether the transaction was flagged as fraudulent | Boolean | True / False |
| 20 | `aml_check_status` | Result of the Anti-Money Laundering (AML) check on the transaction | Categorical | Passed, Failed, Pending, Manual Review, Skipped |
| 21 | `kyc_status` | Status of the Know Your Customer (KYC) identity verification | Categorical | Verified, Pending, Expired, Not Required |
| 22 | `credit_score` | Customer's creditworthiness score (higher = more creditworthy) | Numerical (float) | 300 → 850 |
| 23 | `customer_segment` | Customer category used by the bank | Categorical | Retail, Premium, Private Banking, Business, Corporate |
| 24 | `ip_address` | IP address the transaction was made from | Text | e.g. `206.241.176.171` |
| 25 | `created_at` | Timestamp when the record was created in the bank's system | Datetime (stored as text) | 2023-01-01 → 2023-12-28 |

# Data Exploration

## 1. Load Dataset

In [2]:
df=pd.read_csv('finance_banking_transactions_2022_2025.csv')

In [3]:
df.shape

(52624, 25)

In [4]:
df.head(10)

,transaction_id,account_id,customer_id,customer_name,account_type,account_status,transaction_type,transaction_date,amount,currency,...,is_international,fee_amount,risk_score,fraud_flag,aml_check_status,kyc_status,credit_score,customer_segment,ip_address,created_at
0,TXN-20230000000,ACC-229636759,CUST-616210,Sabine Koch,Checking,Frozen,Transfer,2025-06-14,17101.85,PLN,...,False,0.00,6.28,False,Failed,Pending,592.0,Premium,206.241.176.171,2023-01-13 12:32:00
1,TXN-20230000001,ACC-856806426,CUST-754810,Daniel Boateng,Loan,Frozen,Refund,2022-08-18,45026.38,USD,...,True,0.00,60.60,False,Passed,Expired,686.0,Private Banking,221.29.175.160,2023-02-26 08:58:00
2,TXN-20230000002,ACC-443163624,CUST-644966,Lukas Koch,Credit Card,Closed,Fee,2023-05-18,10658.79,EUR,...,True,0.00,97.67,False,Pending,Expired,763.0,Corporate,199.1.62.209,2023-07-10 15:28:00
3,TXN-20230000003,ACC-949045770,CUST-365821,Mia Weber,Credit Card,active,Interest,2023-09-22,-44113.52,PLN,...,True,13.33,71.52,True,Pending,Pending,388.0,Business,1.156.52.54,2023-02-25 07:14:00
4,TXN-20230000004,ACC-696055802,CUST-161490,Hanna Muller,Mortgage,Closed,Transfer,2022-05-29,-38955.13,CHF,...,True,7.44,51.16,True,Passed,verified,NaN,Corporate,69.62.158.212,2023-03-05 05:06:00
5,TXN-20230000005,ACC-924805099,CUST-937791,Andreas Fischer,Credit Card,Closed,Deposit,2023-01-09,-49119.28,CHF,...,False,2.12,29.34,True,Passed,verified,NaN,Premium,249.185.119.164,2023-01-27 06:15:00
6,TXN-20230000006,ACC-686709111,CUST-150560,Lisa Osei,Investment,Frozen,Interest,2024-04-09,39414.51,GBP,...,True,0.00,79.04,True,Manual Review,verified,605.0,Premium,162.250.185.224,2023-12-01 01:14:00
7,TXN-20230000007,ACC-994438434,CUST-525733,Sabine Hoffmann,Checking,Active,Fee,07-08-2025,-28956.26,GBP,...,True,16.59,51.44,True,Skipped,Not Required,687.0,Retail,149.62.75.5,2023-06-24 13:24:00
8,TXN-20230000008,ACC-874372765,CUST-665975,Andreas Mensah,Mortgage,ACTIVE,Payment,2023-04-25,17010.39,USD,...,False,0.00,96.52,True,Manual Review,Expired,NaN,Corporate,202.91.74.166,2023-09-18 23:12:00
9,TXN-20230000009,ACC-904596408,CUST-633312,Thomas Boateng,Credit Card,ACTIVE,Deposit,2023-04-17,-10896.25,PLN,...,True,12.95,1.82,False,passed,Pending,NaN,Business,76.69.181.113,2023-05-25 00:19:00

## 2. Check Data Types

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 52624 entries, 0 to 52623
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   transaction_id       52624 non-null  str
 1   account_id           52624 non-null  str
 2   customer_id          52624 non-null  str
 3   customer_name        52624 non-null  str
 4   account_type         52624 non-null  str
 5   account_status       52624 non-null  str
 6   transaction_type     52624 non-null  str
 7   transaction_date     52624 non-null  str
 8   amount               52624 non-null  float64
 9   currency             52624 non-null  str
 10  balance_after        52624 non-null  float64
 11  transaction_channel  52624 non-null  str
 12  branch_city          52624 non-null  str
 13  merchant_name        45378 non-null  str
 14  payment_method       52624 non-null  str
 15  is_international     52624 non-null  bool
 16  fee_amount           52624 non-null  float64
 17  risk_score           52624 non-null  float64
 18  fraud_flag           52624 non-null  bool
 19  aml_check_status     52624 non-null  str
 20  kyc_status           52624 non-null  str
 21  credit_score         35451 non-null  float64
 22  customer_segment     52624 non-null  str
 23  ip_address           52624 non-null  str
 24  created_at           52624 non-null  str
dtypes: bool(2), float64(5), str(18)
memory usage: 17.9 MB

**Observation:**
- `transaction_date` and `created_at` are stored as text (`str`) instead of `datetime`.
- `merchant_name` (45,378 non-null) and `credit_score` (35,451 non-null) have fewer values than the 52,624 rows, so they contain missing values.
- All other columns have suitable data types.

## 3. Check Duplicates

In [6]:
df.duplicated().sum()

np.int64(624)

In [7]:
df[df.duplicated()]

,transaction_id,account_id,customer_id,customer_name,account_type,account_status,transaction_type,transaction_date,amount,currency,...,is_international,fee_amount,risk_score,fraud_flag,aml_check_status,kyc_status,credit_score,customer_segment,ip_address,created_at
52000,TXN-20230004774,ACC-715158530,CUST-880085,Felix Schneider,Savings,Dormant,Withdrawal,2023-09-30,-1987.42,GBP,...,False,17.36,15.57,False,Pending,Not Required,535.0,Retail,246.125.201.129,2023-03-24 15:13:00
52001,TXN-20230009906,ACC-478409872,CUST-664476,Thomas Schmidt,Checking,ACTIVE,Fee,2024-06-05,11242.83,PLN,...,True,5.00,91.09,True,Skipped,Not Required,NaN,Retail,155.59.252.225,2023-02-26 02:57:00
52002,TXN-20230017925,ACC-199859104,CUST-273981,Christina Schneider,Loan,Frozen,Refund,2022-11-12,49866.17,EUR,...,True,13.54,65.79,True,passed,Verified,442.0,Private Banking,168.81.250.109,2023-11-03 03:50:00
52003,TXN-20230020898,ACC-345760348,CUST-280438,Sabine Schmidt,Credit Card,Dormant,Transfer,2023-12-30,31182.45,PLN,...,True,0.00,64.82,False,Failed,Pending,378.0,Business,194.12.60.245,2023-08-05 03:41:00
52004,TXN-20230041075,ACC-224875363,CUST-919162,Sophie Sowah,Checking,Frozen,Deposit,01 May 2023,-23352.41,USD,...,True,0.00,1.27,True,Manual Review,verified,434.0,Private Banking,169.188.145.22,2023-11-14 09:25:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52619,TXN-20230014029,ACC-653025656,CUST-334886,Christina Sowah,Credit Card,Frozen,Payment,02-10-2022,5753.41,EUR,...,True,0.00,87.58,False,passed,Verified,NaN,Private Banking,9.191.163.119,2023-05-25 20:00:00
52620,TXN-20230039166,ACC-755323946,CUST-152217,Lukas Bauer,Mortgage,ACTIVE,Payment,2023-03-03,-36721.89,EUR,...,True,0.00,49.35,False,Skipped,Verified,546.0,Business,21.201.94.210,2023-07-17 05:00:00
52621,TXN-20230044663,ACC-970876882,CUST-187736,Paul Becker,Investment,Dormant,Payment,30/09/2023,49127.14,EUR,...,True,22.91,17.89,True,Pending,Verified,319.0,Premium,222.99.169.230,2023-03-19 20:55:00
52622,TXN-20230003784,ACC-712988228,CUST-657814,Paul Boateng,Credit Card,Active,Deposit,10 Apr 2023,38328.82,USD,...,True,0.00,39.75,False,Passed,Pending,666.0,Private Banking,197.215.46.180,2023-12-25 18:45:00
52623,TXN-20230000710,ACC-619154472,CUST-795395,David Agyeman,Checking,ACTIVE,Transfer,2025-11-19,-48822.90,PLN,...,True,0.00,6.57,False,Passed,Not Required,684.0,Retail,27.212.99.108,2023-03-23 17:37:00

**Observation:** There are 624 fully duplicated rows (1.2% of the data). → Will be removed in the cleaning phase.

## 4. Check Summary Statistics for Numerical Columns

In [8]:
df.describe().round(2)

           amount  balance_after  fee_amount  risk_score  credit_score
count    52624.00       52624.00    52624.00    52624.00      35451.00
mean       341.08      249109.77        4.99       49.91        575.44
std      95795.83      143924.04        7.63       28.90        159.01
min   -4737986.89         107.18        0.00        0.01        300.00
25%     -25159.91      124249.14        0.00       24.82        438.00
50%         32.44      248935.86        0.00       49.94        576.00
75%      25243.50      373188.48        9.40       74.92        713.00
max    4091721.74      499987.45       25.00      100.00        850.00

**Observation:**
- `credit_score` has only 35,451 values (out of 52,624), so it has missing values.
- `amount` has negative values (min = -4,737,986.89), although a transaction size should not be negative.
- `amount` has extreme values: the 75th percentile is 25,243.50 but the maximum is 4,091,721.74, which suggests outliers.
- `balance_after` (107 to 499,987), `fee_amount` (0 to 25), `risk_score` (0 to 100) and `credit_score` (300 to 850) are within valid ranges.

## 5. Check Summary Statistics for Categorical Columns

In [9]:
df.describe(include=['str'])

,transaction_id,account_id,customer_id,customer_name,account_type,account_status,transaction_type,transaction_date,currency,transaction_channel,branch_city,merchant_name,payment_method,aml_check_status,kyc_status,customer_segment,ip_address,created_at
count,52624,52624,52624,52624,52624,52624,52624,52624,52624,52624,52624,45378,52624,52624,52624,52624,52624,52624
unique,52000,52000,50510,400,6,6,7,6208,5,7,15,9,6,6,5,5,52000,49344
top,TXN-20230001651,ACC-276905870,CUST-379091,Paul Richter,Investment,active,Payment,2024-10-21,EUR,Online,Hamburg,REWE,Debit Card,Passed,verified,Business,138.173.88.114,2023-02-27 23:19:00
freq,3,3,4,163,8896,8937,7564,46,10650,7641,3608,5135,8856,8915,10695,10620,3,4

**Observations:**
- `transaction_id` has 52,000 unique values out of 52,624 rows, confirming duplicates.
- `account_status`, `payment_method`, `aml_check_status` and `kyc_status` have more unique values than expected, and the top values `active` and `verified` are written in lowercase. This suggests inconsistent letter case.
- `transaction_date` has 6,208 unique values, although 2022–2025 contains only 1,461 days. This suggests that the same date is written in different formats.
- `customer_name` has only 400 unique names for 50,510 customer IDs.
- `ip_address` has a different value for almost every row.
- `merchant_name` has only 45,378 values, so it has missing values.
- `currency` has 5 values, so amounts are in different currencies.
- The most frequent value in each categorical column has a frequency close to the other values, so categories are almost evenly distributed.

## 6. Check Missing Values

In [10]:
df.isna().sum()

transaction_id             0
account_id                 0
customer_id                0
customer_name              0
account_type               0
account_status             0
transaction_type           0
transaction_date           0
amount                     0
currency                   0
balance_after              0
transaction_channel        0
branch_city                0
merchant_name           7246
payment_method             0
is_international           0
fee_amount                 0
risk_score                 0
fraud_flag                 0
aml_check_status           0
kyc_status                 0
credit_score           17173
customer_segment           0
ip_address                 0
created_at                 0
dtype: int64

In [11]:
(df.isna().mean()*100).round(2)

transaction_id          0.00
account_id              0.00
customer_id             0.00
customer_name           0.00
account_type            0.00
account_status          0.00
transaction_type        0.00
transaction_date        0.00
amount                  0.00
currency                0.00
balance_after           0.00
transaction_channel     0.00
branch_city             0.00
merchant_name          13.77
payment_method          0.00
is_international        0.00
fee_amount              0.00
risk_score              0.00
fraud_flag              0.00
aml_check_status        0.00
kyc_status              0.00
credit_score           32.63
customer_segment        0.00
ip_address              0.00
created_at              0.00
dtype: float64

**Observation:** Only 2 columns have missing values:
- `credit_score`: 17,173 missing (32.6%)
- `merchant_name`: 7,246 missing (13.8%)

# Data Cleaning

## Work on a copy so the original data stays unchanged

In [12]:
df_clean = df.copy()

### Drop Unnecessary Columns

In [13]:
df_clean.columns

Index(['transaction_id', 'account_id', 'customer_id', 'customer_name',
       'account_type', 'account_status', 'transaction_type',
       'transaction_date', 'amount', 'currency', 'balance_after',
       'transaction_channel', 'branch_city', 'merchant_name', 'payment_method',
       'is_international', 'fee_amount', 'risk_score', 'fraud_flag',
       'aml_check_status', 'kyc_status', 'credit_score', 'customer_segment',
       'ip_address', 'created_at'],
      dtype='str')

In [14]:
df_clean.drop(['ip_address','customer_name','created_at'], axis=1,inplace=True)

In [15]:
print(df.shape)
print(df_clean.shape)

(52624, 25)
(52624, 22)

**Result:** 3 columns were dropped:
- `ip_address`: has a different value for almost every row, so it has no analytical value.
- `customer_name`: only 400 names for 50,510 customers, so it cannot identify a customer; `customer_id` is used instead.
- `created_at`: a system record timestamp that is not needed, since `transaction_date` is used for time analysis.

The dataset now has 22 columns.

### Drop Duplicates

In [16]:
print('Duplicates before:', df_clean.duplicated().sum())

df_clean.drop_duplicates(inplace=True)

print('Duplicates after:', df_clean.duplicated().sum())
print('Rows remaining:', df_clean.shape[0])

Duplicates before: 624
Duplicates after: 0
Rows remaining: 52000

**Result:** 624 fully duplicated rows were removed, keeping the first occurrence. The dataset now has 52,000 unique transactions.

### In-Depth Check of Numerical Columns

In [17]:
num_cols = df_clean.select_dtypes(include = 'number')

In [18]:
for col in num_cols :
    px.box(data_frame=df_clean,x=col,title=col).show()

**Observation:**
- `amount` has negative values and extreme values far from the box (outliers). → Will be handled in the next steps.
- `balance_after`, `fee_amount`, `risk_score` and `credit_score` are within their valid ranges and need no changes.

### In-Depth Check of Categorical Columns

In [19]:
cat_cols = df_clean.select_dtypes(include='str').columns.drop(
    ['transaction_id', 'account_id', 'customer_id', 'transaction_date']
)
cat_cols

Index(['account_type', 'account_status', 'transaction_type', 'currency',
       'transaction_channel', 'branch_city', 'merchant_name', 'payment_method',
       'aml_check_status', 'kyc_status', 'customer_segment'],
      dtype='str')

In [20]:
for col in cat_cols :
    print(col)
    print(df_clean[col].nunique())
    print(df_clean[col].unique())
    print('-'*100)

account_type
6
<ArrowStringArray>
['Checking', 'Loan', 'Credit Card', 'Mortgage', 'Investment', 'Savings']
Length: 6, dtype: str
----------------------------------------------------------------------------------------------------
account_status
6
<ArrowStringArray>
['Frozen', 'Closed', 'active', 'Active', 'ACTIVE', 'Dormant']
Length: 6, dtype: str
----------------------------------------------------------------------------------------------------
transaction_type
7
<ArrowStringArray>
['Transfer', 'Refund', 'Fee', 'Interest', 'Deposit', 'Payment', 'Withdrawal']
Length: 7, dtype: str
----------------------------------------------------------------------------------------------------
currency
5
<ArrowStringArray>
['PLN', 'USD', 'EUR', 'CHF', 'GBP']
Length: 5, dtype: str
----------------------------------------------------------------------------------------------------
transaction_channel
7
<ArrowStringArray>
['Mobile App', 'Phone', 'ATM', 'SEPA', 'Branch', 'Online', 'Direct Debit']
Length: 7, dtype: str
----------------------------------------------------------------------------------------------------
branch_city
15
<ArrowStringArray>
[   'Hamburg',    'Cologne',  'Stuttgart',    'Dresden',     'Berlin',
     'Bremen', 'Dusseldorf',     'Munich',    'Hanover',  'Nuremberg',
  'Frankfurt',    'Leipzig',   'Dortmund',   'Duisburg',      'Essen']
Length: 15, dtype: str
----------------------------------------------------------------------------------------------------
merchant_name
9
<ArrowStringArray>
[       'Amazon',         'Shell', 'Deutsche Bahn',          'REWE',
             nan,       'Netflix',    'MediaMarkt',          'Lidl',
         'EDEKA',          'Aldi']
Length: 10, dtype: str
----------------------------------------------------------------------------------------------------
payment_method
6
<ArrowStringArray>
['SEPA', 'sepa', 'Cash', 'Bank Transfer', 'Credit Card', 'Debit Card']
Length: 6, dtype: str
----------------------------------------------------------------------------------------------------
aml_check_status
6
<ArrowStringArray>
['Failed', 'Passed', 'Pending', 'Manual Review', 'Skipped', 'passed']
Length: 6, dtype: str
----------------------------------------------------------------------------------------------------
kyc_status
5
<ArrowStringArray>
['Pending', 'Expired', 'verified', 'Not Required', 'Verified']
Length: 5, dtype: str
----------------------------------------------------------------------------------------------------
customer_segment
5
<ArrowStringArray>
['Premium', 'Private Banking', 'Corporate', 'Business', 'Retail']
Length: 5, dtype: str
----------------------------------------------------------------------------------------------------

**Observations:**
- Inconsistent letter case was found in 4 columns, where the same value is written in different forms:
  - `account_status`: active / Active / ACTIVE (6 unique values instead of 4)
  - `payment_method`: SEPA / sepa (6 unique values instead of 5)
  - `aml_check_status`: Passed / passed (6 unique values instead of 5)
  - `kyc_status`: Verified / verified (5 unique values instead of 4)
  → Will be standardized in the next step.
- All other categorical columns contain valid values with no spelling errors or unexpected values.
- All 15 branch cities are in Germany, confirming that this is a German bank.
- Transactions are in 5 currencies (EUR, USD, GBP, CHF, PLN), so amounts cannot be summed without considering the currency.
- `SEPA` appears in both `transaction_channel` and `payment_method`; this is valid, as SEPA can be both the channel and the payment method.
- `merchant_name` contains missing values (NaN). → Will be filled with "Unknown".

### Fix Inconsistent Text Case

In [21]:
df_clean['account_status'] = df_clean['account_status'].replace({'active': 'Active', 'ACTIVE': 'Active'})
df_clean['payment_method'] = df_clean['payment_method'].replace({'sepa': 'SEPA'})
df_clean['aml_check_status'] = df_clean['aml_check_status'].replace({'passed': 'Passed'})
df_clean['kyc_status'] = df_clean['kyc_status'].replace({'verified': 'Verified'})

In [22]:
for col in ['account_status', 'payment_method', 'aml_check_status', 'kyc_status']:
    print(col)
    print(df_clean[col].nunique())
    print(df_clean[col].unique())
    print('-'*100)

account_status
4
<ArrowStringArray>
['Frozen', 'Closed', 'Active', 'Dormant']
Length: 4, dtype: str
----------------------------------------------------------------------------------------------------
payment_method
5
<ArrowStringArray>
['SEPA', 'Cash', 'Bank Transfer', 'Credit Card', 'Debit Card']
Length: 5, dtype: str
----------------------------------------------------------------------------------------------------
aml_check_status
5
<ArrowStringArray>
['Failed', 'Passed', 'Pending', 'Manual Review', 'Skipped']
Length: 5, dtype: str
----------------------------------------------------------------------------------------------------
kyc_status
4
<ArrowStringArray>
['Pending', 'Expired', 'Verified', 'Not Required']
Length: 4, dtype: str
----------------------------------------------------------------------------------------------------

**Result:** Inconsistent letter case was standardized in 4 columns:
- `account_status`: active / ACTIVE → Active (6 → 4 unique values)
- `payment_method`: sepa → SEPA (6 → 5 unique values)
- `aml_check_status`: passed → Passed (6 → 5 unique values)
- `kyc_status`: verified → Verified (5 → 4 unique values)

Each value now appears in a single consistent form.

### Fix Date Formats and Data Types

In [23]:
df['transaction_date'].str.replace(r'\d', '9', regex=True).value_counts()

transaction_date
9999-99-99     39424
99/99/9999      6599
99-99-9999      3229
99 Jul 9999      329
99 Jan 9999      312
99 Dec 9999      309
99 Aug 9999      284
99 Feb 9999      284
99 Nov 9999      276
99 Oct 9999      275
99 Apr 9999      271
99 Jun 9999      263
99 May 9999      262
99 Sep 9999      261
99 Mar 9999      246
Name: count, dtype: int64

In [24]:
dates = df_clean['transaction_date']

# Convert each date format separately

date_iso         = pd.to_datetime(dates, format='%Y-%m-%d', errors='coerce')   # 2024-03-09
date_slash_day   = pd.to_datetime(dates, format='%d/%m/%Y', errors='coerce')   # 06/11/2024 (day first)
date_text        = pd.to_datetime(dates, format='%d %b %Y', errors='coerce')   # 09 Jul 2024
date_dash        = pd.to_datetime(dates, format='%d-%m-%Y', errors='coerce')   # 21-01-2025
date_slash_month = pd.to_datetime(dates, format='%m/%d/%Y', errors='coerce')   # 11/25/2024 (month first)

In [25]:
# Combine all formats into one column.
# Since this is a German bank, ambiguous dates (e.g. 06/11/2024) are treated as
# day-first (DD/MM/YYYY), the standard date format in Germany.
# Month-first is tried last, only for dates that cannot be day-first (e.g. 11/25/2024).

df_clean['transaction_date'] = (date_iso
                                .fillna(date_slash_day)
                                .fillna(date_text)
                                .fillna(date_dash)
                                .fillna(date_slash_month))

In [26]:
print('Data type:', df_clean['transaction_date'].dtype)
print('Missing dates:', df_clean['transaction_date'].isna().sum())
print('From:', df_clean['transaction_date'].min().date())
print('To:', df_clean['transaction_date'].max().date())

Data type: datetime64[us]
Missing dates: 0
From: 2022-01-01
To: 2025-12-31

**Result:** `transaction_date` was converted from text to `datetime`.
- The column contained 4 different date formats (`YYYY-MM-DD`, `DD/MM/YYYY` or `MM/DD/YYYY`, `DD Mon YYYY`, `DD-MM-YYYY`); each format was parsed separately and then combined.
- 1,879 slash dates could only be read as month-first (e.g. `11/25/2024`), showing that the data mixes day-first and month-first formats.
- Ambiguous slash dates (e.g. `06/11/2024`) were treated as day-first, since this is a German bank and day-first is the standard format in Germany.
- No dates were lost (0 missing), and all dates fall between 2022-01-01 and 2025-12-31.

**Limitation:** Because both formats exist in the data, some ambiguous dates may actually be month-first. This cannot be verified from the data.

**Impact:** The effect is small. Only 2,620 dates (about 5% of the data) are ambiguous, and in the worst case a transaction is assigned to the wrong day and month within the same year. Analysis by year is not affected, because the year is always clear.

### Fill Missing Merchant Names Column

In [27]:
print('Missing before:', df_clean['merchant_name'].isna().sum())

df_clean['merchant_name'] = df_clean['merchant_name'].fillna('Unknown')

print('Missing after:', df_clean['merchant_name'].isna().sum())

Missing before: 7165
Missing after: 0

In [28]:
df_clean['merchant_name'].value_counts()

merchant_name
Unknown          7165
REWE             5064
Lidl             5039
Shell            5017
Aldi             5001
Deutsche Bahn    4991
MediaMarkt       4960
Amazon           4953
EDEKA            4946
Netflix          4864
Name: count, dtype: int64

**Result:** 7,165 missing values in `merchant_name` were filled with "Unknown" (7,165 instead of 7,246 because some missing values were in the removed duplicates). The rows were kept so that their other columns can still be used in the analysis.

### Convert Amount to Absolute Values

In [29]:
print('Negative amounts before:', (df_clean['amount'] < 0).sum())

# Remove the sign: the sign is random, so amount will represent the transaction size only

df_clean['amount'] = df_clean['amount'].abs()

print('Negative amounts after:', (df_clean['amount'] < 0).sum())

Negative amounts before: 25890
Negative amounts after: 0

**Result:** 25,890 negative amounts (about 50% of all transactions) were converted to positive values. The sign is not reliable, so `amount` now represents the transaction size only, and `transaction_type` shows the direction of money.

### Flag Outliers in Amount (Feature Engineering)

In [30]:
# Calculate the IQR upper limit for amount

q1 = df_clean['amount'].quantile(0.25)
q3 = df_clean['amount'].quantile(0.75)
iqr = q3 - q1
upper_limit = q3 + 1.5 * iqr

print('Upper limit:', round(upper_limit, 2))

# Flag outliers instead of removing them (feature engineering)

df_clean['is_outlier'] = df_clean['amount'] > upper_limit
print('Number of outliers:', df_clean['is_outlier'].sum())

# Show the range of the outlier amounts

print('Outlier range:', round(df_clean[df_clean['is_outlier']]['amount'].min(), 2), 'to',
       round(df_clean[df_clean['is_outlier']]['amount'].max(), 2))

Upper limit: 75680.1
Number of outliers: 220
Outlier range: 78268.2 to 4737986.89

In [31]:
# Compare fraud rate, average risk score and international share between normal transactions and outliers

df_clean.groupby('is_outlier')[['fraud_flag', 'risk_score', 'is_international']].mean()

            fraud_flag  risk_score  is_international
is_outlier
False         0.500560   49.915668          0.499324
True          0.504545   50.299955          0.468182

In [32]:
print('Mean (all):', round(df_clean['amount'].mean(), 2))
print('Mean (without outliers):', round(df_clean[~df_clean['is_outlier']]['amount'].mean(), 2))
print('Median (all):', round(df_clean['amount'].median(), 2))

Mean (all): 29008.07
Mean (without outliers): 25038.73
Median (all): 25202.58

**Result:** A new column `is_outlier` was created using the IQR method (upper limit = 75,680). 220 transactions (from 78K to 4.7 million) were flagged as outliers.

- Outliers were **kept**, not removed, because in banking large transactions may signal fraud or important valid activity.
- Outliers are very similar to normal transactions: fraud rate (50.5% vs 50.1%), average risk score (50.3 vs 49.9) and international share (46.8% vs 49.9%).
- Outliers raise the mean amount from 25,039 to 29,008, while the median stays at about 25,203. → The **median** will be used instead of the mean, and a **log scale** will be used in charts.

### Handle Missing Values in Credit Score

**Decision:** `credit_score` has 17,173 missing values (32.6%, as shown in the Missing Values check). These values are **kept as NaN** and will be excluded only from analyses that use the credit score, because filling about a third of the column with estimated values would distort the distribution.

### Note on Currencies

In [33]:
df_clean['currency'].value_counts()

currency
EUR    10535
GBP    10425
PLN    10360
USD    10356
CHF    10324
Name: count, dtype: int64

In [34]:
# Median amount in each currency
df_clean.groupby('currency')['amount'].median().round(0)

currency
CHF    25337.0
EUR    25352.0
GBP    25338.0
PLN    24966.0
USD    25081.0
Name: amount, dtype: float64

**Decision:** `currency` has 5 valid values and needs no cleaning. However, the median amount is almost the same in all 5 currencies (about 25,000), which shows that amounts were generated without considering the currency. Converting or adding them would give misleading results, so the analysis will be based on **transaction counts** instead of values.

### Reset Index

In [35]:
# Reset the index after removing duplicates

df_clean = df_clean.reset_index(drop=True)

print('Rows:', len(df_clean))
print('Last index:', df_clean.index.max())

Rows: 52000
Last index: 51999

**Result:** The index was reset after removing duplicates, so rows are now numbered from 0 to 51,999 without gaps.

### Final Check and Save Clean Data

In [36]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 52000 entries, 0 to 51999
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   transaction_id       52000 non-null  str
 1   account_id           52000 non-null  str
 2   customer_id          52000 non-null  str
 3   account_type         52000 non-null  str
 4   account_status       52000 non-null  str
 5   transaction_type     52000 non-null  str
 6   transaction_date     52000 non-null  datetime64[us]
 7   amount               52000 non-null  float64
 8   currency             52000 non-null  str
 9   balance_after        52000 non-null  float64
 10  transaction_channel  52000 non-null  str
 11  branch_city          52000 non-null  str
 12  merchant_name        52000 non-null  str
 13  payment_method       52000 non-null  str
 14  is_international     52000 non-null  bool
 15  fee_amount           52000 non-null  float64
 16  risk_score           52000 non-null  float64
 17  fraud_flag           52000 non-null  bool
 18  aml_check_status     52000 non-null  str
 19  kyc_status           52000 non-null  str
 20  credit_score         35013 non-null  float64
 21  customer_segment     52000 non-null  str
 22  is_outlier           52000 non-null  bool
dtypes: bool(3), datetime64[us](1), float64(5), str(14)
memory usage: 13.9 MB

**Observation:** The clean dataset has 52,000 rows and 23 columns (including the new `is_outlier` column). `transaction_date` is now `datetime`, and the only column with missing values is `credit_score`, which was kept as NaN on purpose.

In [37]:
df_clean.to_csv('finance_banking_transactions_clean.csv', index=False)

### Cleaning Summary

| # | Issue | Action | Result |
|---|---|---|---|
| 1 | Unnecessary columns | Dropped `ip_address`, `customer_name`, `created_at` | 25 → 22 columns |
| 2 | Duplicated rows | Dropped duplicates | 624 rows removed (52,000 left) |
| 3 | Inconsistent text case | Standardized 4 columns | e.g. active / ACTIVE → Active |
| 4 | Mixed date formats stored as text | Parsed each format and converted to `datetime` | 0 dates lost |
| 5 | Missing `merchant_name` | Filled with "Unknown" | 7,165 values filled |
| 6 | Unreliable negative amounts | Absolute value | 25,890 values converted |
| 7 | Outliers in `amount` | Kept and flagged with `is_outlier` | 220 outliers flagged |
| 8 | Missing `credit_score` | Kept as NaN | Missing values kept on purpose |
| 9 | Multiple currencies | Analysis based on counts | No conversion |
| 10 | Index gaps | Reset index | 0 to 51,999 |

# Exploratory Data Analysis (EDA)

## Analysis Questions

The analysis focuses on the bank's business performance and supports decisions for each stakeholder: Executive Management, Digital & Product, Marketing, Branch Operations and Compliance.

**Q1. Business Growth:** How did the number of transactions and active customers change from 2022 to 2025?
*Stakeholder:* Executive Management

**Q2. Large Transactions:** Where do large transactions come from, and are they well controlled?
*Stakeholder:* Executive Management & Relationship Managers

**Q3. Channels & Digital Banking:** How do customers use digital and non-digital channels, and is digital usage growing?
*Stakeholder:* Digital & Product Team

**Q4. Customers & Products:** Which products does each customer segment use?
*Stakeholder:* Marketing Team

**Q5. Branch Performance:** Which branch cities are growing and which are declining?
*Stakeholder:* Branch Operations

**Q6. Compliance & Risk:** How many transactions have compliance red flags, and does the risk score identify fraud?
*Stakeholder:* Compliance Team

## Preparation

**Note:** *Digital channels* are channels the customer uses remotely through the internet (Online and Mobile App). ATM is a self-service channel that requires physical presence, so it is counted as non-digital, together with Branch, Phone, SEPA and Direct Debit.

In [38]:
# Feature engineering for the analysis.

df_clean['year'] = df_clean['transaction_date'].dt.year

# Group channels into Digital (Online, Mobile App) and Non-Digital (all others)

df_clean['channel_group'] = np.where(df_clean['transaction_channel'].isin(['Online', 'Mobile App']),
                                     'Digital', 'Non-Digital')

In [39]:
def rate_by(data, group_col, flag_col):
    """Return the % of True values of flag_col in each group."""
    return (data.groupby(group_col)[flag_col].mean() * 100).round(2)

## Univariate Analysis
Each variable is analyzed alone to understand its distribution before answering the questions.

### Numerical Variables

In [40]:
df_clean[['amount', 'fee_amount', 'risk_score', 'credit_score']].describe().round(2)

           amount  fee_amount  risk_score  credit_score
count    52000.00    52000.00    52000.00      35013.00
mean     29008.07        4.99       49.92        575.48
std      90432.49        7.64       28.90        159.11
min          0.00        0.00        0.01        300.00
25%      12481.75        0.00       24.82        437.00
50%      25202.58        0.00       49.94        576.00
75%      37761.09        9.41       74.92        713.00
max    4737986.89       25.00      100.00        850.00

In [41]:
# amount is highly skewed, so a log scale is used to make the box readable

px.box(df_clean, x='amount', log_x=True, title='Distribution of Amount (log scale)').show()

for col in ['fee_amount', 'risk_score', 'credit_score']:
    px.histogram(df_clean, x=col, title=f'Distribution of {col}').show()

In [42]:
# Percentage of transactions with no fee

((df_clean['fee_amount'] == 0).mean() * 100).round(1)

np.float64(60.1)

**Observation:**
- `amount`: the median is 25,203, but the maximum is 4.7 million, so the data is right-skewed because of a few very large transactions. The median is used instead of the mean.
- `fee_amount`: 60.1% of transactions have no fee, and the maximum fee is 25.
- `risk_score`: values are spread evenly from 0 to 100 (median ≈ 50).
- `credit_score`: values are spread evenly from 300 to 850 (median 576), based on the 35,013 available values.

### Categorical Variables

In [43]:
cat_cols = ['transaction_channel', 'account_type', 'account_status', 'currency', 'fraud_flag']

for col in cat_cols:
    counts = (df_clean[col].value_counts(normalize=True) * 100).round(1)
    px.bar(counts, text_auto=True, title=f'{col} (%)').update_traces(texttemplate='%{y}%').update_layout(yaxis_title='Percentage (%)', showlegend=False).show()

px.pie(df_clean, names='customer_segment', title='Customer Segment').show()

**Observation:**
- `transaction_channel`, `account_type`, `currency` and `customer_segment`: all categories have almost equal shares (e.g. each of the 7 channels ≈ 14%, each of the 5 currencies ≈ 20%).
- `account_status`: 50.1% of accounts are Active; Dormant, Frozen and Closed are about 16.6% each.
- `fraud_flag`: 50.1% of transactions are flagged as fraud, which is far from real banking (usually below 1%) and confirms that the data is synthetic.

## Bivariate and Multivariate Analysis
In this section, each analysis question is answered by comparing two or more variables.

### Q1. Business Growth: How did the number of transactions and active customers change from 2022 to 2025?

In [44]:
plot_df = df_clean.groupby('year').agg(transactions=('transaction_id', 'count'),
                                       active_customers=('customer_id', 'nunique')).reset_index()
plot_df

   year  transactions  active_customers
0  2022         13095             13001
1  2023         13113             13000
2  2024         12973             12851
3  2025         12819             12730

In [45]:
px.bar(data_frame=plot_df, x='year',
       y=['transactions', 'active_customers'],
       barmode='group',
       text_auto=True,
       title='Transactions and Active Customers per Year',
       labels={'value': 'Count', 'variable': ''}).update_xaxes(dtick=1)

In [46]:
plot_df = df_clean.groupby(df_clean['transaction_date'].dt.to_period('M').dt.to_timestamp())['transaction_id'].count().reset_index()
plot_df

   transaction_date  transaction_id
0        2022-01-01            1160
1        2022-02-01            1103
2        2022-03-01            1117
3        2022-04-01            1023
4        2022-05-01            1100
5        2022-06-01            1115
6        2022-07-01            1127
7        2022-08-01            1064
8        2022-09-01            1058
9        2022-10-01            1063
10       2022-11-01            1070
11       2022-12-01            1095
12       2023-01-01            1135
13       2023-02-01            1065
14       2023-03-01            1123
15       2023-04-01            1024
16       2023-05-01            1131
17       2023-06-01            1062
18       2023-07-01            1124
19       2023-08-01            1125
20       2023-09-01            1049
21       2023-10-01            1100
22       2023-11-01            1099
23       2023-12-01            1076
24       2024-01-01            1108
25       2024-02-01            1071
26       2024-03-01            1136
27       2024-04-01            1101
28       2024-05-01            1067
29       2024-06-01            1024
30       2024-07-01            1112
31       2024-08-01            1112
32       2024-09-01            1104
33       2024-10-01            1083
34       2024-11-01            1018
35       2024-12-01            1037
36       2025-01-01            1131
37       2025-02-01             994
38       2025-03-01            1104
39       2025-04-01            1031
40       2025-05-01            1096
41       2025-06-01            1062
42       2025-07-01            1062
43       2025-08-01            1095
44       2025-09-01            1015
45       2025-10-01            1099
46       2025-11-01            1019
47       2025-12-01            1111

In [47]:
px.area(data_frame=plot_df, x='transaction_date', y='transaction_id',
        title='Monthly Number of Transactions',
        labels={'transaction_date': 'Month', 'transaction_id': 'Num of Transactions'})

**Observation:**
- Transactions are stable at about 13,000 per year (13,095 in 2022 → 12,819 in 2025), with a small decline of about 1% in 2024 and 2025.
- Active customers follow the same pattern (13,001 → 12,730), so the decline comes from fewer customers, not from less usage.
- Monthly transactions stay between 994 and 1,160, with no strong seasonality.

**Recommendation:**
- Run retention campaigns to stop the slow decline in active customers, and monitor them monthly as an early warning sign.
- Attract new customers through marketing campaigns and referral rewards.
- Encourage customers to make more transactions (e.g., cashback, loyalty points or lower fees), since each active customer makes only about one transaction per year.

### Q2. Large Transactions: Where do large transactions come from, and are they well controlled?

In [48]:
# Number and share of large transactions (outliers)
plot_df = df_clean['is_outlier'].value_counts().reset_index()
plot_df['share_%'] = (plot_df['count'] / plot_df['count'].sum() * 100).round(2)
plot_df

   is_outlier  count  share_%
0       False  51780    99.58
1        True    220     0.42

**Note:** Large transactions are compared by **count**, not by total value. The amounts have the same distribution in all 5 currencies (median ≈ 25,000), which shows they were generated without considering the currency, so adding or comparing their values would not be reliable.

In [49]:
# % of large transactions in each account type, customer segment and channel
for col in ['account_type', 'customer_segment', 'transaction_channel']:
    plot_df = rate_by(df_clean, col, 'is_outlier').sort_values(ascending=False).reset_index()
    px.bar(data_frame=plot_df, x=col, y='is_outlier', text_auto=True,
           title=f'Large Transactions Rate by {col}',
           labels={'is_outlier': 'Large Transactions (%)'}).show()

In [50]:
plot_df = df_clean[df_clean['is_outlier']].groupby(['account_status', 'aml_check_status'])['transaction_id'].count().reset_index()
plot_df

   account_status aml_check_status  transaction_id
0          Active           Failed              13
1          Active    Manual Review              20
2          Active           Passed              42
3          Active          Pending              16
4          Active          Skipped              21
5          Closed           Failed               3
6          Closed    Manual Review               4
7          Closed           Passed              12
8          Closed          Pending               6
9          Closed          Skipped               6
10        Dormant           Failed               5
11        Dormant    Manual Review               7
12        Dormant           Passed              11
13        Dormant          Pending               5
14        Dormant          Skipped               8
15         Frozen           Failed               9
16         Frozen    Manual Review               5
17         Frozen           Passed               7
18         Frozen          Pending              14
19         Frozen          Skipped               6

In [51]:
px.bar(data_frame=plot_df, x='account_status', y='transaction_id', color='aml_check_status', text_auto=True,
       title='Large Transactions by Account Status and AML Check',
       labels={'transaction_id': 'Num of Large Transactions', 'account_status': 'Account Status',
               'aml_check_status': 'AML Check'})

**Observation:**
- There are only 220 large transactions (0.42%), ranging from 78K to 4.7 million.
- They are most common in Loan and Mortgage accounts and in the Mobile App channel, and spread almost equally across customer segments.
- 49% of the accounts that made large transactions are currently Frozen, Dormant or Closed, and 37% of large transactions had their AML check Skipped or Pending.

**Recommendation:**
- Review the large transactions on accounts that are now Frozen, Dormant or Closed, to check whether these transactions were the reason for the status change.
- Make a completed AML check mandatory for every large transaction.
- Assign relationship managers to the customers behind large transactions.

### Q3. Channels & Digital Banking: How do customers use digital and non-digital channels, and is digital usage growing?

In [52]:
plot_df = df_clean.groupby('channel_group').agg(transactions=('transaction_id', 'count'),
                                                active_customers=('customer_id', 'nunique')).reset_index()
plot_df['share_%'] = (plot_df['transactions'] / plot_df['transactions'].sum() * 100).round(1)
plot_df

  channel_group  transactions  active_customers  share_%
0       Digital         15011             14879     28.9
1   Non-Digital         36989             36233     71.1

In [53]:
px.pie(data_frame=plot_df, names='channel_group', values='transactions',
       title='Digital vs Non-Digital Transactions')

In [54]:
# Transactions per channel per year, and the % change from 2022 to 2025
plot_df = pd.crosstab(df_clean['transaction_channel'], df_clean['year'])
plot_df['change_%'] = ((plot_df[2025] / plot_df[2022] - 1) * 100).round(1)
plot_df['trend'] = np.where(plot_df['change_%'] >= 0, 'Growing', 'Declining')
plot_df = plot_df.sort_values('change_%').reset_index()
plot_df

year transaction_channel  2022  2023  2024  2025  change_%      trend
0                   SEPA  1919  1905  1859  1744      -9.1  Declining
1                  Phone  1881  1875  1830  1795      -4.6  Declining
2                 Online  1919  1903  1887  1838      -4.2  Declining
3                    ATM  1887  1921  1832  1820      -3.6  Declining
4             Mobile App  1901  1808  1922  1833      -3.6  Declining
5           Direct Debit  1844  1864  1796  1843      -0.1  Declining
6                 Branch  1744  1837  1847  1946      11.6    Growing

In [55]:
px.bar(data_frame=plot_df, x='change_%', y='transaction_channel', orientation='h', color='trend', text_auto=True,
       color_discrete_map={'Growing': '#81c784', 'Declining': '#e57373'},
       title='Change in Transactions from 2022 to 2025 by Channel (%)',
       labels={'change_%': 'Change from 2022 to 2025 (%)', 'transaction_channel': 'Channel', 'trend': ''})

**Observation:**
- Digital channels (Online + Mobile App) handle only 28.9% of transactions, while non-digital channels handle 71.1%.
- Digital usage is not growing: Online fell by 4.2% and Mobile App by 3.6% from 2022 to 2025.
- Branch is the only growing channel (+11.6%), while all other channels declined.

**Recommendation:**
- Launch a digital adoption campaign (e.g., rewards or lower fees for Mobile App and Online transactions).
- Study why customers are returning to branches, and move simple branch services to the app.

### Q4. Customers & Products: Which products does each customer segment use?

In [56]:
# % of each account type within each customer segment (each row adds up to 100%)
plot_df = pd.crosstab(df_clean['customer_segment'], df_clean['account_type'], normalize='index').mul(100).round(1)
plot_df

account_type      Checking  Credit Card  Investment  Loan  Mortgage  Savings
customer_segment
Business              16.4         16.6        16.3  16.8      17.0     16.9
Corporate             16.9         15.9        16.8  17.0      16.9     16.6
Premium               16.4         17.0        17.0  16.3      16.9     16.4
Private Banking       16.7         16.9        17.2  16.4      16.9     16.0
Retail                16.7         16.8        17.3  16.9      15.9     16.4

In [57]:
px.imshow(plot_df, text_auto=True, color_continuous_scale='Blues', zmin=0,
          title='Product Mix per Customer Segment (%)',
          labels={'x': 'Account Type', 'y': 'Customer Segment', 'color': '%'})

**Observation:**
- Every customer segment uses all 6 products in almost equal shares (15.9% to 17.3%), so no segment prefers a specific product.
- In real banking, segments usually have different needs (e.g., Corporate customers use more Checking and Loan accounts, and Private Banking customers use more Investment accounts), so this equal mix shows that products are not tailored to each segment.

**Recommendation:**
- Design segment-specific product packages (e.g., investment products for Private Banking and Premium customers, and business loans for Corporate customers).

### Q5. Branch Performance: Which branch cities are growing and which are declining?

In [58]:
# Total % change in transactions from 2022 to 2025 for each branch city
plot_df = pd.crosstab(df_clean['branch_city'], df_clean['year'])
plot_df['change_%'] = ((plot_df[2025] / plot_df[2022] - 1) * 100).round(1)
plot_df['trend'] = np.where(plot_df['change_%'] >= 0, 'Growing', 'Declining')
plot_df = plot_df.sort_values('change_%').reset_index()
plot_df

year branch_city  2022  2023  2024  2025  change_%      trend
0       Dortmund   887   878   899   814      -8.2  Declining
1       Duisburg   863   857   898   802      -7.1  Declining
2        Cologne   888   915   808   833      -6.2  Declining
3      Frankfurt   904   885   896   848      -6.2  Declining
4        Hamburg   962   835   868   904      -6.0  Declining
5        Leipzig   842   891   880   798      -5.2  Declining
6         Bremen   906   886   826   873      -3.6  Declining
7        Hanover   901   892   833   872      -3.2  Declining
8     Dusseldorf   860   836   812   856      -0.5  Declining
9      Stuttgart   857   864   901   854      -0.4  Declining
10        Munich   872   883   884   886       1.6    Growing
11       Dresden   830   892   911   850       2.4    Growing
12        Berlin   883   871   833   906       2.6    Growing
13     Nuremberg   822   836   894   855       4.0    Growing
14         Essen   818   892   830   868       6.1    Growing

In [59]:
px.bar(data_frame=plot_df, x='change_%', y='branch_city', orientation='h', color='trend', text_auto=True,
       color_discrete_map={'Growing': '#81c784', 'Declining': '#e57373'},
       title='Total Change in Transactions from 2022 to 2025 by Branch City (%)',
       labels={'change_%': 'Change from 2022 to 2025 (%)', 'branch_city': 'Branch City', 'trend': ''})

In [60]:
# % change in transactions compared to the previous year, for each branch city
plot_df = df_clean.groupby(['branch_city', 'year'])['transaction_id'].count().reset_index(name='transactions')
plot_df['change_%'] = (plot_df.groupby('branch_city')['transactions'].pct_change() * 100).round(1)
plot_df = plot_df.dropna()
plot_df['trend'] = np.where(plot_df['change_%'] >= 0, 'Growth', 'Decline')
plot_df

   branch_city  year  transactions  change_%    trend
1       Berlin  2023           871      -1.4  Decline
2       Berlin  2024           833      -4.4  Decline
3       Berlin  2025           906       8.8   Growth
5       Bremen  2023           886      -2.2  Decline
6       Bremen  2024           826      -6.8  Decline
7       Bremen  2025           873       5.7   Growth
9      Cologne  2023           915       3.0   Growth
10     Cologne  2024           808     -11.7  Decline
11     Cologne  2025           833       3.1   Growth
13    Dortmund  2023           878      -1.0  Decline
14    Dortmund  2024           899       2.4   Growth
15    Dortmund  2025           814      -9.5  Decline
17     Dresden  2023           892       7.5   Growth
18     Dresden  2024           911       2.1   Growth
19     Dresden  2025           850      -6.7  Decline
21    Duisburg  2023           857      -0.7  Decline
22    Duisburg  2024           898       4.8   Growth
23    Duisburg  2025           802     -10.7  Decline
25  Dusseldorf  2023           836      -2.8  Decline
26  Dusseldorf  2024           812      -2.9  Decline
27  Dusseldorf  2025           856       5.4   Growth
29       Essen  2023           892       9.0   Growth
30       Essen  2024           830      -7.0  Decline
31       Essen  2025           868       4.6   Growth
33   Frankfurt  2023           885      -2.1  Decline
34   Frankfurt  2024           896       1.2   Growth
35   Frankfurt  2025           848      -5.4  Decline
37     Hamburg  2023           835     -13.2  Decline
38     Hamburg  2024           868       4.0   Growth
39     Hamburg  2025           904       4.1   Growth
41     Hanover  2023           892      -1.0  Decline
42     Hanover  2024           833      -6.6  Decline
43     Hanover  2025           872       4.7   Growth
45     Leipzig  2023           891       5.8   Growth
46     Leipzig  2024           880      -1.2  Decline
47     Leipzig  2025           798      -9.3  Decline
49      Munich  2023           883       1.3   Growth
50      Munich  2024           884       0.1   Growth
51      Munich  2025           886       0.2   Growth
53   Nuremberg  2023           836       1.7   Growth
54   Nuremberg  2024           894       6.9   Growth
55   Nuremberg  2025           855      -4.4  Decline
57   Stuttgart  2023           864       0.8   Growth
58   Stuttgart  2024           901       4.3   Growth
59   Stuttgart  2025           854      -5.2  Decline

In [61]:
px.scatter(data_frame=plot_df, x='year', y='branch_city', color='trend', symbol='trend', text='change_%',
           color_discrete_map={'Growth': '#81c784', 'Decline': '#e57373'},
           symbol_map={'Growth': 'triangle-up', 'Decline': 'triangle-down'}, height=600,
           title='Yearly Growth or Decline in Transactions by Branch City (%)',
           labels={'year': 'Year (compared to previous year)', 'branch_city': 'Branch City', 'trend': ''}
          ).update_traces(marker_size=16, textposition='middle right').update_xaxes(dtick=1)

**Observation:**
- 10 of 15 branches declined from 2022 to 2025, led by Dortmund (-8.2%) and Duisburg (-7.1%). Essen grew the most (+6.1%).
- Dortmund, Duisburg and Leipzig dropped sharply in 2025 only, so their decline is recent.
- Hamburg and Berlin recovered after bad years, and Munich is the only branch that grew every year.

**Recommendation:**
- Investigate what changed in 2025 in Dortmund, Duisburg and Leipzig.
- Run a market scan for the declining branches to understand their local market and customer needs, and adjust their services to grow transactions.
- Run a Net Promoter Score (NPS) survey to measure customer satisfaction with the bank's service and products, and collect their suggestions for improvement.
- Introduce staff incentives linked to branch targets to encourage growth.
- Apply the practices of Munich, Hamburg and Berlin to the declining branches.

### Q6. Compliance & Risk: How many transactions have compliance red flags, and does the risk score identify fraud?

In [62]:
# A transaction has a red flag if its account, KYC or AML status is a problem
red_flags = pd.DataFrame({
    'Account currently Closed or Frozen': df_clean['account_status'].isin(['Closed', 'Frozen']),
    'KYC Expired or Pending': df_clean['kyc_status'].isin(['Expired', 'Pending']),
    'AML Failed or Skipped': df_clean['aml_check_status'].isin(['Failed', 'Skipped']),
})
red_flags['At least one red flag'] = red_flags.any(axis=1)

plot_df = (red_flags.mean() * 100).round(1).rename_axis('red_flag').reset_index(name='share_%')
plot_df

                             red_flag  share_%
0  Account currently Closed or Frozen     33.2
1              KYC Expired or Pending     39.8
2               AML Failed or Skipped     33.0
3               At least one red flag     73.1

In [63]:
px.bar(data_frame=plot_df, x='red_flag', y='share_%', text_auto=True,
       title='Transactions with Compliance Red Flags (%)',
       labels={'red_flag': 'Red Flag', 'share_%': 'Share of Transactions (%)'})

In [64]:
plot_df = pd.crosstab(df_clean['kyc_status'], df_clean['aml_check_status'])
plot_df

aml_check_status  Failed  Manual Review  Passed  Pending  Skipped
kyc_status
Expired             1748           1684    3523     1729     1689
Not Required        1742           1727    3362     1724     1760
Pending             1714           1775    3459     1718     1653
Verified            3386           3533    7097     3497     3480

In [65]:
px.imshow(plot_df, text_auto=True, color_continuous_scale='Blues',
          title='KYC Status vs AML Check Status (Number of Transactions)',
          labels={'x': 'AML Check', 'y': 'KYC Status', 'color': 'Transactions'})

In [66]:
# Fraud rate in each risk score band
df_clean['risk_band'] = pd.cut(df_clean['risk_score'], bins=[0, 20, 40, 60, 80, 100], include_lowest=True,
                               labels=['0-20', '20-40', '40-60', '60-80', '80-100'])
plot_df = rate_by(df_clean, 'risk_band', 'fraud_flag').reset_index()
plot_df

  risk_band  fraud_flag
0      0-20       49.90
1     20-40       50.23
2     40-60       49.65
3     60-80       49.70
4    80-100       50.83

In [67]:
px.bar(data_frame=plot_df, x='risk_band', y='fraud_flag', text_auto=True,
       title='Fraud Rate by Risk Score Band',
       labels={'risk_band': 'Risk Score Band', 'fraud_flag': 'Fraud Rate (%)'}).update_yaxes(range=[0, 100])

**Observation:**
- 73.1% of transactions have at least one compliance red flag, and KYC Expired or Pending is the most common (39.8%).
- 6,982 transactions passed the AML check although the customer's KYC was Expired or Pending.
- The fraud rate is about 50% in every risk score band, so the risk score does not identify fraud.

**Recommendation:**
- Block transactions for customers with expired KYC until their documents are renewed.
- Do not allow an AML "Passed" status unless KYC is Verified or Not Required.
- Review and retrain the risk scoring model, since it currently does not separate fraud from normal transactions.

# Conclusion

## Key Findings

| # | Question | Main Finding |
|---|---|---|
| Q1 | Business Growth | Transactions and active customers are stable at about 13,000 per year, with a small decline of about 1% in 2024 and 2025. |
| Q2 | Large Transactions | Only 220 transactions (0.42%), mostly in Loan and Mortgage accounts and the Mobile App. 49% are linked to accounts that are now Frozen, Dormant or Closed, and 37% had their AML check Skipped or Pending. |
| Q3 | Channels & Digital Banking | Digital channels handle only 28.9% of transactions and are declining, while Branch is the only growing channel (+11.6%). |
| Q4 | Customers & Products | All customer segments use the 6 products in almost equal shares, so products are not tailored to each segment. |
| Q5 | Branch Performance | 10 of 15 branches declined from 2022 to 2025. Dortmund, Duisburg and Leipzig dropped sharply in 2025, while Munich is the only branch that grew every year. |
| Q6 | Compliance & Risk | 73.1% of transactions have at least one compliance red flag, 6,982 passed AML with expired or pending KYC, and the risk score does not identify fraud. |

## Top Priorities for the Bank

1. **Fix compliance controls (urgent):** block transactions for customers with expired KYC, and make a completed AML check mandatory, especially for large transactions.
2. **Rebuild the risk scoring model:** the current risk score does not separate fraud from normal transactions.
3. **Grow digital banking:** encourage Mobile App and Online usage through rewards or lower fees, and move simple branch services to the app.
4. **Tailor products to segments:** create product packages designed for each customer segment.
5. **Support declining branches:** run a market scan and a Net Promoter Score (NPS) survey, and introduce staff incentives linked to branch targets.

## Limitations

- **Synthetic data:** the fraud rate (about 50%) and the almost equal shares of all categories are not realistic, so the findings show the analysis approach rather than real banking behavior.
- **Multiple currencies:** amounts have the same distribution in all 5 currencies (median ≈ 25,000), which shows they were generated without considering the currency. Converting or adding them would give misleading results, so the analysis is based on transaction counts instead of values.
- **Account status:** `account_status` shows the current status of the account, not its status at the time of each transaction.
- **One account per transaction:** every transaction has a different `account_id`, so it is not possible to analyze how many accounts or products each customer holds.
- **Missing credit scores:** about one third of `credit_score` values are missing, so credit score results are based on the available values only.
- **Ambiguous dates:** dates such as 06/11/2024 were treated as day-first (European format), which may place a small number of transactions in the wrong month.